import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'label-sm': ['Plus Jakarta Sans'],
                'display-mobile': ['Plus Jakarta Sans'],
                'body-md': ['Plus Jakarta Sans'],
                'headline-lg': ['Plus Jakarta Sans'],
                'body-lg': ['Plus Jakarta Sans'],
                'numeric-pos': ['Plus Jakarta Sans'],
                'label-lg': ['Plus Jakarta Sans'],
                'label-md': ['Plus Jakarta Sans'],
                'headline-sm': ['Plus Jakarta Sans'],
                'display-lg': ['Plus Jakarta Sans'],
                'headline-md': ['Plus Jakarta Sans'],
                'body-sm': ['Plus Jakarta Sans'],
            },
            fontSize: {
                'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
                'display-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '800' }],
                'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'headline-lg': ['28px', { lineHeight: '34px', letterSpacing: '-0.015em', fontWeight: '700' }],
                'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'numeric-pos': ['24px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' }],
                'label-lg': ['14px', { lineHeight: '20px', fontWeight: '600' }],
                'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
                'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
                'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
                'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' }],
                'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
            },
            colors: {
                'secondary-container': '#fecf9d',
                'on-surface': '#27180c',
                'surface-dim': '#f1d5c0',
                'surface-tint': '#78583a',
                'tertiary-fixed-dim': '#d5c4b3',
                'surface-bright': '#fff8f5',
                'outline-variant': '#d3c4b9',
                'tertiary-fixed': '#f2dfce',
                'on-secondary-container': '#79562e',
                'on-error-container': '#93000a',
                'on-surface-variant': '#4f453c',
                'on-primary-fixed-variant': '#5d4125',
                'primary-fixed': '#ffdcbf',
                'primary-fixed-dim': '#e8bf9a',
                'background': '#fff8f5',
                'primary-container': '#7c5c3e',
                'on-background': '#27180c',
                'surface': '#fff8f5',
                'on-error': '#ffffff',
                'on-primary': '#ffffff',
                'inverse-primary': '#e8bf9a',
                'on-primary-container': '#ffd8b6',
                'secondary-fixed': '#ffddba',
                'on-secondary-fixed': '#2b1700',
                'tertiary': '#54483c',
                'on-tertiary': '#ffffff',
                'on-tertiary-container': '#eedccb',
                'secondary-fixed-dim': '#ecbe8e',
                'error-container': '#ffdad6',
                'surface-container-high': '#ffe3cf',
                'on-secondary': '#ffffff',
                'surface-container': '#ffeadc',
                'surface-variant': '#faddc8',
                'on-tertiary-fixed': '#231a10',
                'surface-container-highest': '#faddc8',
                'error': '#ba1a1a',
                'surface-container-low': '#fff1e9',
                'tertiary-container': '#6d6052',
                'secondary': '#7a582f',
                'surface-container-lowest': '#ffffff',
                'inverse-on-surface': '#ffede2',
                'inverse-surface': '#3e2d1f',
                'on-primary-fixed': '#2c1601',
                'on-secondary-fixed-variant': '#5f401a',
                'on-tertiary-fixed-variant': '#504538',
                'primary': '#624528',
                'outline': '#81756b',
            },
            spacing: {
                'space-2xs': '0.25rem',
                'space-xs': '0.5rem',
                'space-sm': '0.75rem',
                'space-md': '1rem',
                'space-lg': '1.25rem',
                'space-xl': '1.5rem',
                'space-2xl': '2rem',
                'space-3xl': '3rem',
                'touch-target-min': '2.75rem',
                'gutter-mobile': '1rem',
                'gutter-desktop': '1.5rem',
                'max-mobile-width': '24.375rem',
            },
            borderRadius: {
                DEFAULT: '0.25rem',
                lg: '0.5rem',
                xl: '0.75rem',
                full: '9999px',
            },
        },
    },

    plugins: [forms],
};
